jdk:
  - openjdk17

android:
  components:
    - build-tools-34.0.0
    - ndk-bundle
    - cmake;3.22.1

before_install:
  - yes | sdkmanager "ndk;25.1.8937393"
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.1.8937393
  - wget https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar
  - wget https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.1/jaxb-impl-2.3.1.jar
  - wget https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-core/2.3.1/jaxb-core-2.3.1.jar || true
  - export CLASSPATH=$CLASSPATH:$(pwd)/jaxb-api-2.3.1.jar:$(pwd)/jaxb-impl-2.3.1.jar:$(pwd)/jaxb-core-2.3.1.jar

install:
  - ./gradlew clean

script:
  - ./gradlew build