jdk:
  version: openjdk17

before_install:
  - apt-get update && apt-get install -y cmake ninja-build
  - wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
  - unzip android-ndk-r21e-linux-x86_64.zip -d /usr/local/
  - export ANDROID_NDK_HOME=/usr/local/android-ndk-r21e

install:
  - ./gradlew clean

script:
  - ./gradlew build