jdk:
  - openjdk17

android:
  components:
    - build-tools-34.0.0
    - ndk-bundle
    - cmake;3.22.1

before_install:
  - yes | sdkmanager "ndk;25.1.8937393"
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.1.8937393

install:
  - ./gradlew clean

script:
  - ./gradlew build